---
armor_enchant_names:
  # head
  - arcanum_of_rapidity
  # chest
  - greater_stats
  # bracer
  - superior_strength
  # gloves
  - greater_agility
  # legs
  - arcanum_of_rapidity
  # feet

mh_enchant_names: 
  - superior_striking
oh_enchant_names: 
  - greater_striking


