---
armor_names:
### head
  - bloodfang_hood
### neck
  - onyxia_tooth_pendant
### shoulders
  - nightslayer_shoulder_pads
### back
  - cape_of_the_black_baron
### chest
  - nightslayer_chestpiece
### bracers
  - nightslayer_bracelets
### gloves
  - nightslayer_gloves
### belt
  - nightslayer_belt
### legs
  - bloodfang_pants
### boots
  - boots_of_the_shadow_flame
  #  - shadowcraft_boots
### rings
  - master_dragonslayers_ring
  - tarnished_elven_ring
### trinkets
#  - royal_seal_of_eldre_thalas
  - hand_of_justice
  - blackhands_breadth
### ranged
  - satyrs_bow
mh_name:
  gutgore_ripper
oh_name:
  distracting_dagger
