---
# assassination
improved_eviscerate: 0
malice: 5 
ruthlessness: 2
improved_slice_and_dice: 3
relentless_strikes: 1
lethality: 5
# combat
improved_sinister_strike: 2
improved_backstab: 3
precision: 5 
dagger_specialization: 5
dual_wield_specialization: 5
sword_specialization: 0 # TODO
weapon_expertise: 2
aggression: 2
# subtlety
opportunity: 5
