items:
  armor_names:
  - bloodfang_hood
  - onyxia_tooth_pendant
  - nightslayer_shoulder_pads
  - cape_of_the_black_baron
  - nightslayer_gloves
  mh_name:
  - gutgore_ripper
  oh_name:
  - gutgore_ripper
enchants:
  armor_enchant_names:
  - lesser_agility
  - greater_agility
  mh_enchant_names:
  - superior_striking
  - elemental_grinding_stone
  oh_enchant_names:
  - greater_striking
  - dense_grinding_stone
talents:
  aggression: 0
  dagger_specialization: 0
  dual_wield_specialization: 5
  improved_backstab: 3
  improved_eviscerate: 0
  improved_sinister_strike: 0
  improved_slice_and_dice: 0
  lethality: 5
  malice: 0
  opportunity: 0
  precision: 5
  relentless_strikes: 0
  ruthlessness: 0
  sword_specialization: 0
  weapon_expertise: 0
